name: Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            envkey_DATABASE_URL: ${secrets.DATABASE_URL}
            envkey_POSTGRES_USER: ${secrets.POSTGRES_USER}
            envkey_POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
            envkey_POSTGRES_DB: ${secrets.POSTGRES_DB}
            directory: back-end/
            file_name: .env
            fail_on_empty: true